/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PrimeSieveJNI */

#ifndef _Included_PrimeSieveJNI
#define _Included_PrimeSieveJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PrimeSieveJNI
 * Method:    getPrimeList
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_PrimeSieveJNI_getPrimeList
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
